### ISSUE TITLE
Improve style

### ISSUE THREAD

**Issue by vitobreda** [vitobreda/Tetris#1]
Change style of game to improve the gameplay

**Comment by RajSolai** [comment]
Fine I can take that issue and improve the quality of ui !

**Comment by vitobreda** [comment]
> Fine I can take that issue and improve the quality of ui !

thanks to help

**Comment by Pratim14** [comment]
I would like to work on your website

**Comment by RajSolai** [comment]
@vitobreda  Hey pal , I completed the work but the branch can't be merged automatically so it might take some time , Sorry for delay , Pardon me !

**Comment by RajSolai** [comment]
The Made the Revamp in the game UI , Hope you like it @vitobreda  👍️ #5 
![ezgif com-gif-maker](https://user-images.githubusercontent.com/54436424/95103870-cb08db00-0752-11eb-99b6-60007a6e4ce9.gif)
P.S. The glitch in the border is just due to the screen recorder issues
